#!/bin/bash -login
#PBS -l walltime=48:00:00,nodes=01:ppn=8,mem=20gb
#PBS -q main
#PBS -M adina.chuang@gmail.com
#PBS -m abe
#PBS -A ged-intel11

module load BLAST

workingdir=/mnt/scratch/howead/hmp-mock/compare-assemblies/raw-diginorm
cd $workingdir

RAW=raw-contigs.fa.300.renamed
KNOTS=diginorm-assembly.fa.300.renamed
blastall -i $RAW -d $KNOTS -o $RAW.x.$KNOTS.blastnout.m8 -p blastn -a 8 -m 8
blastall -i $KNOTS -d $RAW -o $KNOTS.x.$RAW.blastnout.m8 -p blastn -a 8 -m 8

python ~/scripts/blast-calc-cover/calc-blast-cover2.py $RAW $KNOTS.x.$RAW.blastnout > $RAW.in.$KNOTS.coverage.txt

python ~/scripts/blast-calc-cover/calc-blast-cover2.py $KNOTS $RAW.x.$KNOTS.blastnout > $KNOTS.in.$RAW.coverage.txt
